import { useState } from "react";

const people = [
  { initials: "A", name: "Aaron, 29", distance: "2.4 km", color: "sand" },
  { initials: "M", name: "Miles, 31", distance: "4.8 km", color: "sage" },
  { initials: "J", name: "Jules, 27", distance: "7.1 km", color: "plum" },
];

function PhonePreview() {
  const [active, setActive] = useState(0);
  const person = people[active];
  return <div className="phone"><div className="phone-notch" /><div className="phone-top"><b><span className="heart">♥</span> Punch <em>Desk</em></b><span>•••</span></div><div className={`portrait ${person.color}`}><span>{person.initials}</span><div className="portrait-copy"><strong>{person.name} <i>✓</i></strong><small>⌖ {person.distance} · Online now</small></div></div><div className="phone-actions"><button onClick={() => setActive((active + 2) % people.length)}>×</button><button className="gold" onClick={() => setActive((active + 1) % people.length)}>♥</button></div><div className="phone-tabs"><span className="selected">⌾<small>Discover</small></span><span>♡<small>Likes</small></span><span>♙<small>Profile</small></span></div></div>;
}

function Landing() {
  return <><header className="site-nav"><a className="wordmark"><span className="mark">♥</span> Punch <em>Desk</em></a><nav><a href="#discover">Discover</a><a href="#how">How it works</a><a href="#safety">Safety</a></nav><button className="nav-cta">Get started <span>↗</span></button></header><main><section className="hero"><div className="hero-copy"><p className="eyebrow">A DATING ENGINE FOR REAL CONNECTION</p><h1>Closer feels <i>better.</i></h1><p className="hero-lead">Meet people who are actually nearby. Punch Desk makes space for conversations that feel like they could become something.</p><div className="hero-actions"><button className="primary-cta">Get started <span>↗</span></button><button className="text-cta">Explore features <span>↓</span></button></div><div className="proof"><span className="avatar-stack"><b>A</b><b>M</b><b>J</b></span><span>Made for thoughtful<br />people nearby.</span></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><PhonePreview /><div className="floating-note"><span className="gold-dot" /><div><b>New connection</b><small>Someone nearby liked you</small></div></div></div></section><section className="feature-section" id="discover"><div className="section-intro"><p className="eyebrow">THE GOOD STUFF</p><h2>Less noise.<br /><i>More signal.</i></h2><p>Every part of Punch Desk is designed around your comfort, your pace, and where life is happening right now.</p></div><div className="feature-grid"><Feature icon="⌖" title="Actually nearby" text="Discover people within your chosen radius. No exact locations, ever." /><Feature icon="✦" title="Thoughtful matching" text="Intentional profiles and interests give conversations somewhere to start." /><Feature icon="♡" title="Private by design" text="You decide what you share, including photos and presence." /></div></section><section className="quote-section" id="safety"><div className="quote-mark">“</div><blockquote>Good connection is not about finding more people. It is about finding the right distance to be yourself.</blockquote><p>— The Punch Desk principle</p></section><section className="cta-section" id="how"><p className="eyebrow">YOUR NEXT HELLO IS CLOSER THAN YOU THINK</p><h2>Make room for<br /><i>something real.</i></h2><button className="primary-cta">Get started <span>↗</span></button></section></main><footer><a className="wordmark"><span className="mark">♥</span> Punch <em>Desk</em></a><span>© 2026 Punch Desk · Privacy · Safety · Terms</span></footer></>;
}

function Feature({ icon, title, text }: { icon: string; title: string; text: string }) { return <article className="feature-card"><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p><a>Learn more <span>↗</span></a></article>; }

function Admin() {
  return <div className="admin-shell"><aside><a className="wordmark"><span className="mark">♥</span> Punch <em>Desk</em></a><p className="side-label">Workspace</p>{["Overview", "People", "Matches", "Messages", "Subscriptions", "Reports"].map((item, index) => <a className={index === 0 ? "side-link active" : "side-link"} key={item}><span>{["⌂", "♙", "♡", "◌", "◇", "⚑"][index]}</span>{item}</a>)}<p className="side-label">Engine</p>{["App configuration", "Themes", "Profile fields", "Audit log"].map((item) => <a className="side-link" key={item}><span>·</span>{item}</a>)}<div className="admin-user"><span className="user-avatar">S</span><div><b>Samira Khan</b><small>Super admin</small></div><span>•••</span></div></aside><section className="admin-main"><div className="admin-top"><div><p className="eyebrow">MONDAY, 12 AUGUST 2026</p><h1>Good morning, Samira.</h1></div><button className="admin-profile">S <span>⌄</span></button></div><div className="metric-grid"><Metric label="Total people" value="12,480" delta="+8.4%" /><Metric label="Active this week" value="8,921" delta="+12.1%" /><Metric label="New matches" value="1,204" delta="+5.8%" /><Metric label="Subscription revenue" value="₹8.4L" delta="+18.2%" /></div><div className="dashboard-grid"><div className="chart-card"><div className="card-head"><div><h2>People are finding each other</h2><p>New registrations · Last 30 days</p></div><button>30 days⌄</button></div><div className="chart"><div className="grid-lines" /><svg viewBox="0 0 800 240" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#D4AF37" stopOpacity=".26" /><stop offset="1" stopColor="#D4AF37" stopOpacity="0" /></linearGradient></defs><path d="M0 204 C50 180 76 198 120 160 S182 180 220 132 S286 170 330 110 S400 130 452 94 S520 116 565 70 S630 106 680 42 S740 62 800 22 L800 240 L0 240Z" fill="url(#chartFill)" /><path d="M0 204 C50 180 76 198 120 160 S182 180 220 132 S286 170 330 110 S400 130 452 94 S520 116 565 70 S630 106 680 42 S740 62 800 22" fill="none" stroke="#D4AF37" strokeWidth="3" /></svg></div><div className="chart-labels"><span>12 Jul</span><span>19 Jul</span><span>26 Jul</span><span>02 Aug</span><span>12 Aug</span></div></div><div className="activity-card"><div className="card-head"><div><h2>Latest activity</h2><p>Real-time engine signals</p></div><a>View all ↗</a></div>{["New match created", "Premium plan started", "Profile reported"].map((item, index) => <div className="activity-row" key={item}><span className={`activity-dot dot-${index}`} /><div><b>{item}</b><small>{["A match between Aaron and Theo", "Alex upgraded to Premium", "Review needed from a member"][index]}</small></div><time>{["2m", "18m", "42m"][index]}</time></div>)}</div></div></section></div>;
}

function Metric({ label, value, delta }: { label: string; value: string; delta: string }) { return <div className="metric"><p>{label}<span>↗</span></p><strong>{value}</strong><small><b>{delta}</b> vs last period</small></div>; }

export function App() { const [mode, setMode] = useState<"landing" | "admin">("landing"); return <><div className="mode-switch"><button className={mode === "landing" ? "chosen" : ""} onClick={() => setMode("landing")}>Landing</button><button className={mode === "admin" ? "chosen" : ""} onClick={() => setMode("admin")}>Admin preview</button></div>{mode === "landing" ? <Landing /> : <Admin />}</>; }